
package pprogramming3assignmentone;

import java.awt.Dimension;
import java.awt.FlowLayout;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author rndm
 */
public class Table extends javax.swing.JPanel {

    /**
     * Creates new form Table
     */
    public Table(ReadCSV csv) {
        setVisible(true);
        initComponents();
        
        String[] columnNames = {"Timestamp", "Values"};
        //JFileChooser fc = new JFileChooser();
                
        //int returnVal = fc.showDialog(this, "Attach");
        
        //fc.getSelectedFile().getAbsolutePath()
                
        //csv = new CSV();
        
        
        
        Object[][] data = new Object[csv.getCsvData().size()][3];
        
        for (int i = 0; i < csv.getCsvData().size(); i++) {
//            for (int j = 0; j < 2; j++) {
//                data[i][j] = csv.getCsvData().get(i)[j];
//            } 
            data[i][0] = csv.getCsvData().get(i)[0];
            data[i][1] = csv.getCsvData().get(i)[2];
        }
        
        JTable jTable1 = new JTable(data, columnNames);
        jTable1.setBackground(getBackground());
        //table.setPreferredSize(new Dimension(200,200));
        jTable1.setPreferredScrollableViewportSize(new Dimension(getWidth() / 2, 70));
        //table.setEnabled(false);
        //table.setFillsViewportHeight(true);
        jTable1.setAutoCreateRowSorter(true);
        
        TableRowSorter<TableModel> sorter 
        = new TableRowSorter<>(jTable1.getModel());
        jTable1.setRowSorter(sorter);
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        
        //TableColumn column;
        
        for (int i = 0; i < 2; i++) {
            jTable1.getColumnModel().getColumn(i).setCellRenderer( centerRenderer );
            
        }
        
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(jTable1.getSize().width / 2);
        //column.setPreferredWidth(table.getPreferredScrollableViewportSize().width / 2);      //custom size
        
        jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
                
        jTable1.setDefaultRenderer(String.class, centerRenderer);
        
        jScrollPane1.add(jTable1);
        
//        ArrayList <RowSorter.SortKey> sortKeys = new ArrayList<>();
//        sortKeys.add(new RowSorter.SortKey(1, SortOrder.ASCENDING));
//        sortKeys.add(new RowSorter.SortKey(0, SortOrder.ASCENDING));
//        sorter.setSortKeys(sortKeys);
                
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD, 17));
        jLabel1.setText("CSV File");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel1)
                        .addGap(0, 290, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
