/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pembeddedminor;

import java.awt.Color;

/**
 *
 * @author rndm
 */
public class UI extends javax.swing.JFrame {
    /**
     * Creates new form UI
     */
    public UI() {
        initComponents();  
        //jFrame1A.add(new EmbeddedSensor(jFrame1A));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1A = new javax.swing.JFrame();
        jPanel1A = new javax.swing.JPanel();
        jFrame2A = new javax.swing.JFrame();
        jPanel2A = new javax.swing.JPanel();
        jFrame3A = new javax.swing.JFrame();
        jPanel3A = new javax.swing.JPanel();
        jFrame4A = new javax.swing.JFrame();
        jPanel4A = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        jFrame1A.setBounds(new java.awt.Rectangle(1, 1, 160, 480));
        jFrame1A.setIconImages(null);
        jFrame1A.setLocationByPlatform(true);
        jFrame1A.setUndecorated(true);
        jFrame1A.setResizable(false);
        jFrame1A.setType(java.awt.Window.Type.UTILITY);
        jFrame1A.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFrame1AMouseClicked(evt);
            }
        });
        jFrame1A.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFrame1AFocusLost(evt);
            }
        });

        jPanel1A.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1A.setBorder(new javax.swing.border.LineBorder(javax.swing.UIManager.getDefaults().getColor("Button.shadow"), 1, true));
        jPanel1A.setEnabled(false);

        org.jdesktop.layout.GroupLayout jPanel1ALayout = new org.jdesktop.layout.GroupLayout(jPanel1A);
        jPanel1A.setLayout(jPanel1ALayout);
        jPanel1ALayout.setHorizontalGroup(
            jPanel1ALayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 363, Short.MAX_VALUE)
        );
        jPanel1ALayout.setVerticalGroup(
            jPanel1ALayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 396, Short.MAX_VALUE)
        );

        jFrame1A.getContentPane().add(jPanel1A, java.awt.BorderLayout.CENTER);

        jFrame1A.getAccessibleContext().setAccessibleParent(jPanel1);

        jFrame2A.setBounds(new java.awt.Rectangle(1, 1, 160, 120));
        jFrame2A.setIconImages(null);
        jFrame2A.setLocationByPlatform(true);
        jFrame2A.setUndecorated(true);
        jFrame2A.setResizable(false);
        jFrame2A.setType(java.awt.Window.Type.UTILITY);
        jFrame2A.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFrame2AMouseClicked(evt);
            }
        });
        jFrame2A.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFrame1AFocusLost(evt);
            }
        });

        jPanel2A.setBackground(new java.awt.Color(255, 255, 0));
        jPanel2A.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(160, 160, 160), 1, true));
        jPanel2A.setEnabled(false);

        org.jdesktop.layout.GroupLayout jPanel2ALayout = new org.jdesktop.layout.GroupLayout(jPanel2A);
        jPanel2A.setLayout(jPanel2ALayout);
        jPanel2ALayout.setHorizontalGroup(
            jPanel2ALayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 156, Short.MAX_VALUE)
        );
        jPanel2ALayout.setVerticalGroup(
            jPanel2ALayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 116, Short.MAX_VALUE)
        );

        jFrame2A.getContentPane().add(jPanel2A, java.awt.BorderLayout.CENTER);

        jFrame3A.setBounds(new java.awt.Rectangle(1, 1, 160, 120));
        jFrame3A.setIconImages(null);
        jFrame3A.setLocationByPlatform(true);
        jFrame3A.setUndecorated(true);
        jFrame3A.setResizable(false);
        jFrame3A.setType(java.awt.Window.Type.UTILITY);
        jFrame3A.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFrame3AMouseClicked(evt);
            }
        });
        jFrame3A.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFrame1AFocusLost(evt);
            }
        });

        jPanel3A.setBackground(new java.awt.Color(0, 255, 0));
        jPanel3A.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(160, 160, 160), 1, true));
        jPanel3A.setEnabled(false);

        org.jdesktop.layout.GroupLayout jPanel3ALayout = new org.jdesktop.layout.GroupLayout(jPanel3A);
        jPanel3A.setLayout(jPanel3ALayout);
        jPanel3ALayout.setHorizontalGroup(
            jPanel3ALayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 156, Short.MAX_VALUE)
        );
        jPanel3ALayout.setVerticalGroup(
            jPanel3ALayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 116, Short.MAX_VALUE)
        );

        jFrame3A.getContentPane().add(jPanel3A, java.awt.BorderLayout.CENTER);

        jFrame4A.setBounds(new java.awt.Rectangle(1, 1, 160, 120));
        jFrame4A.setIconImages(null);
        jFrame4A.setLocationByPlatform(true);
        jFrame4A.setUndecorated(true);
        jFrame4A.setResizable(false);
        jFrame4A.setType(java.awt.Window.Type.UTILITY);
        jFrame4A.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFrame4AMouseClicked(evt);
            }
        });
        jFrame4A.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFrame1AFocusLost(evt);
            }
        });

        jPanel4A.setBackground(new java.awt.Color(0, 0, 255));
        jPanel4A.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(160, 160, 160), 1, true));
        jPanel4A.setEnabled(false);

        org.jdesktop.layout.GroupLayout jPanel4ALayout = new org.jdesktop.layout.GroupLayout(jPanel4A);
        jPanel4A.setLayout(jPanel4ALayout);
        jPanel4ALayout.setHorizontalGroup(
            jPanel4ALayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 156, Short.MAX_VALUE)
        );
        jPanel4ALayout.setVerticalGroup(
            jPanel4ALayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 116, Short.MAX_VALUE)
        );

        jFrame4A.getContentPane().add(jPanel4A, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Embedded Systems");
        setAlwaysOnTop(true);
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(200, 480));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(4, 0));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(160, 160, 160)));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.setPreferredSize(new java.awt.Dimension(160, 120));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UI.this.mouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });
        jPanel1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                jPanel1AncestorMoved(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 154, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 98, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(160, 160, 160)));
        jPanel2.setAlignmentX(0.0F);
        jPanel2.setAlignmentY(0.0F);
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.setPreferredSize(new java.awt.Dimension(160, 120));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UI.this.mouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });
        jPanel2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                jPanel2AncestorMoved(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 154, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 98, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(160, 160, 160)));
        jPanel3.setAlignmentX(0.0F);
        jPanel3.setAlignmentY(0.0F);
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.setPreferredSize(new java.awt.Dimension(160, 120));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UI.this.mouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });
        jPanel3.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                jPanel3AncestorMoved(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 154, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 98, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(160, 160, 160)));
        jPanel4.setAlignmentX(0.0F);
        jPanel4.setAlignmentY(0.0F);
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.setPreferredSize(new java.awt.Dimension(160, 120));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UI.this.mouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });
        jPanel4.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                jPanel4AncestorMoved(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 154, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 98, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    // <editor-fold defaultstate="collapsed" desc="MouseEvents"> 
    private void jFrame1AMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFrame1AMouseClicked
//        jFrame1A.setAlwaysOnTop(true);
//        jFrame2A.setAlwaysOnTop(false);
//        jFrame3A.setAlwaysOnTop(false);
//        jFrame4A.setAlwaysOnTop(false);
    }//GEN-LAST:event_jFrame1AMouseClicked

    private void jFrame2AMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFrame2AMouseClicked
//        jFrame1A.setAlwaysOnTop(false);
//        jFrame2A.setAlwaysOnTop(true);
//        jFrame3A.setAlwaysOnTop(false);
//        jFrame4A.setAlwaysOnTop(false);
    }//GEN-LAST:event_jFrame2AMouseClicked

    private void jFrame3AMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFrame3AMouseClicked
//        jFrame1A.setAlwaysOnTop(false);
//        jFrame2A.setAlwaysOnTop(false);
//        jFrame3A.setAlwaysOnTop(true);
//        jFrame4A.setAlwaysOnTop(false);
    }//GEN-LAST:event_jFrame3AMouseClicked

    private void jFrame4AMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFrame4AMouseClicked
//        jFrame1A.setAlwaysOnTop(false);
//        jFrame2A.setAlwaysOnTop(false);
//        jFrame3A.setAlwaysOnTop(false);
//        jFrame4A.setAlwaysOnTop(true);
    }//GEN-LAST:event_jFrame4AMouseClicked
        
    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        jFrame2A.setBounds(this.getX() + this.getWidth() + 10, jPanel1.getLocationOnScreen().y, 380, 480);        
        jFrame2A.setVisible(true);
        //clicked2 = !clicked2;
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        jFrame3A.setBounds(this.getX() + this.getWidth() + 10, jPanel1.getLocationOnScreen().y, 380, 480);        
        jFrame3A.setVisible(true);
        //clicked3 = !clicked3;
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        jFrame4A.setBounds(this.getX() + this.getWidth() + 10, jPanel1.getLocationOnScreen().y, 380, 480);        
        jFrame4A.setVisible(true);
        //clicked4 = !clicked4;
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jPanel1AncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel1AncestorMoved
        //jFrame1A.setBounds(this.getX() + this.getWidth() + 10, this.getY(), 380, 480);
    }//GEN-LAST:event_jPanel1AncestorMoved

    private void jPanel2AncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel2AncestorMoved
        //jFrame2A.setBounds(this.getX() + this.getWidth() + 10, this.getY(), 380, 480);
    }//GEN-LAST:event_jPanel2AncestorMoved

    private void jPanel3AncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel3AncestorMoved
        //jFrame3A.setBounds(this.getX() + this.getWidth() + 10, this.getY(), 380, 480);
    }//GEN-LAST:event_jPanel3AncestorMoved

    private void jPanel4AncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel4AncestorMoved
        //jFrame4A.setBounds(this.getX() + this.getWidth() + 10, this.getY(), 380, 480);
    }//GEN-LAST:event_jPanel4AncestorMoved

    private void jFrame1AFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFrame1AFocusLost
        evt.getComponent().setVisible(false);
    }//GEN-LAST:event_jFrame1AFocusLost

    private void mouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseExited
        evt.getComponent().setBackground(new Color(245,245,245));
    }//GEN-LAST:event_mouseExited

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        evt.getComponent().setBackground(Color.WHITE);
    }//GEN-LAST:event_jPanel1MouseEntered

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        jFrame1A.setBounds(this.getX() + this.getWidth() + 10, jPanel1.getLocationOnScreen().y, 380, 480);
        jFrame1A.setVisible(true);
        //clicked1 = !clicked1;
    }//GEN-LAST:event_jPanel1MouseClicked
    
    // </editor-fold>
    
    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {                
                new UI().setVisible(true);
            }
        });
        
        
    }    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame jFrame1A;
    private javax.swing.JFrame jFrame2A;
    private javax.swing.JFrame jFrame3A;
    private javax.swing.JFrame jFrame4A;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel1A;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel2A;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel3A;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel4A;
    // End of variables declaration//GEN-END:variables
}
