/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pembeddedminor;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.Rectangle;
import java.util.ArrayList;

/**
 *
 * @author rndm
 */
public class UI extends javax.swing.JFrame {
    /**
     * Creates new form UI
     */
    public static ArrayList<Integer> y1 = new ArrayList<>();
    public static ArrayList<Integer> y2 = new ArrayList<>();
    public static ArrayList<Integer> y3 = new ArrayList<>();
    public static ArrayList<Integer> y4 = new ArrayList<>();
    
    int xPos=0;
    int posX=0,posY=0;
    
    private boolean sensor1Show = true;
    private boolean sensor2Show = true;
    private boolean sensor4Show = true;
    private boolean sensor3Show = true;
    
    public UI() {        
        initComponents(); 
        
        sensor1 = new EmbeddedSensor(jLabel1, y1);        
        jPanel1A.add(sensor1);
                
        sensor2 = new EmbeddedSensor(jLabel2, y2);
        jPanel2A.add(sensor2);
        
        sensor3 = new EmbeddedSensor(jLabel3, y3);
        jPanel3A.add(sensor3);
        
        sensor4 = new EmbeddedSensor(jLabel4, y4);        
        jPanel4A.add(sensor4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1A = new javax.swing.JFrame();
        jPanel1A = new javax.swing.JPanel(){
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                Graphics2D g2d = (Graphics2D)g;
                GradientPaint w2w = new GradientPaint(0,0,jPanel1.getBackground(),this.getWidth(), 0, new Color(230,230,230, 0xA0));
                g2d.setPaint(w2w);
                g2d.fill (new Rectangle(0, 0, this.getWidth(), this.getHeight()));
                g2d.setColor(Color.DARK_GRAY);
                g2d.drawString("MAX", this.getWidth() - 27, 12);
                g2d.drawString("MIN", this.getWidth() - 27, 117);
            }
        };
        jLabel1 = new javax.swing.JLabel();
        jFrame2A = new javax.swing.JFrame();
        jPanel2A = new javax.swing.JPanel(){
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                Graphics2D g2d = (Graphics2D)g;
                GradientPaint w2w = new GradientPaint(0,0,jPanel2.getBackground(),this.getWidth(), 0, new Color(230,230,230, 0xA0));
                g2d.setPaint(w2w);
                g2d.fill (new Rectangle(0, 0, this.getWidth(), this.getHeight()));
            }
        };
        jLabel2 = new javax.swing.JLabel();
        jFrame3A = new javax.swing.JFrame();
        jPanel3A = new javax.swing.JPanel(){
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                Graphics2D g2d = (Graphics2D)g;
                GradientPaint w2w = new GradientPaint(0,0,jPanel3.getBackground(),this.getWidth(), 0, new Color(230,230,230, 0xA0));
                g2d.setPaint(w2w);
                g2d.fill (new Rectangle(0, 0, this.getWidth(), this.getHeight()));
            }
        };
        jLabel3 = new javax.swing.JLabel();
        jFrame4A = new javax.swing.JFrame();
        jPanel4A = new javax.swing.JPanel(){
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                Graphics2D g2d = (Graphics2D)g;
                GradientPaint w2w = new GradientPaint(0,0,jPanel4.getBackground(),this.getWidth(), 0, new Color(230,230,230, 0xA0));
                g2d.setPaint(w2w);
                g2d.fill (new Rectangle(0, 0, this.getWidth(), this.getHeight()));
            }
        };
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel(){
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                Graphics2D g2d = (Graphics2D)g;
                GradientPaint w2w = new GradientPaint(0, 0, new Color(230,230,230, 0xA0),this.getWidth(), 0, jPanel1.getBackground());
                g2d.setPaint(w2w);
                g2d.fill (new Rectangle(0, 0, this.getWidth(), this.getHeight()));
            }
        };
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel(){
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                Graphics2D g2d = (Graphics2D)g;
                GradientPaint w2w = new GradientPaint(0, 0, new Color(230,230,230, 0xA0).brighter(),this.getWidth(), 0, jPanel2.getBackground());
                g2d.setPaint(w2w);
                g2d.fill (new Rectangle(0, 0, this.getWidth(), this.getHeight()));
            }
        };
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel(){
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                Graphics2D g2d = (Graphics2D)g;
                GradientPaint w2w = new GradientPaint(0, 0, new Color(230,230,230, 0xA0).brighter(),this.getWidth(), 0, jPanel3.getBackground());
                g2d.setPaint(w2w);
                g2d.fill (new Rectangle(0, 0, this.getWidth(), this.getHeight()));
            }
        };
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel(){
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                Graphics2D g2d = (Graphics2D)g;
                GradientPaint w2w = new GradientPaint(0, 0, new Color(230,230,230, 0xA0).brighter(),this.getWidth(), 0, jPanel4.getBackground());
                g2d.setPaint(w2w);
                g2d.fill (new Rectangle(0, 0, this.getWidth(), this.getHeight()));
            }
        };
        jLabel8 = new javax.swing.JLabel();

        jFrame1A.setAlwaysOnTop(true);
        jFrame1A.setBounds(new java.awt.Rectangle(1, 1, 150, 120));
        jFrame1A.setIconImages(null);
        jFrame1A.setUndecorated(true);
        jFrame1A.setResizable(false);
        jFrame1A.setType(java.awt.Window.Type.UTILITY);
        jFrame1A.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jFrame1AMouseWheelMoved(evt);
            }
        });
        jFrame1A.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jFrame1AMouseDragged(evt);
            }
        });

        jPanel1A.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1A.setAlignmentX(1.0F);
        jPanel1A.setAlignmentY(1.0F);

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getSize()+10f));
        jLabel1.setLabelFor(jPanel1);
        jLabel1.setText("255");
        jLabel1.setName("sensor1"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel1ALayout = new org.jdesktop.layout.GroupLayout(jPanel1A);
        jPanel1A.setLayout(jPanel1ALayout);
        jPanel1ALayout.setHorizontalGroup(
            jPanel1ALayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 127, Short.MAX_VALUE)
            .add(jPanel1ALayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPanel1ALayout.createSequentialGroup()
                    .add(0, 47, Short.MAX_VALUE)
                    .add(jLabel1)
                    .add(0, 47, Short.MAX_VALUE)))
        );
        jPanel1ALayout.setVerticalGroup(
            jPanel1ALayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 118, Short.MAX_VALUE)
            .add(jPanel1ALayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPanel1ALayout.createSequentialGroup()
                    .add(0, 46, Short.MAX_VALUE)
                    .add(jLabel1)
                    .add(0, 46, Short.MAX_VALUE)))
        );

        jFrame1A.getContentPane().add(jPanel1A, java.awt.BorderLayout.CENTER);

        jFrame1A.getAccessibleContext().setAccessibleParent(jPanel1);

        jFrame2A.setAlwaysOnTop(true);
        jFrame2A.setBounds(new java.awt.Rectangle(1, 1, 150, 120));
        jFrame2A.setIconImages(null);
        jFrame2A.setUndecorated(true);
        jFrame2A.setResizable(false);
        jFrame2A.setType(java.awt.Window.Type.UTILITY);

        jPanel2A.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2A.setAlignmentX(1.0F);
        jPanel2A.setAlignmentY(1.0F);

        jLabel2.setFont(jLabel2.getFont().deriveFont(jLabel2.getFont().getSize()+10f));
        jLabel2.setLabelFor(jPanel1);
        jLabel2.setText("255");
        jLabel2.setName("sensor2"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel2ALayout = new org.jdesktop.layout.GroupLayout(jPanel2A);
        jPanel2A.setLayout(jPanel2ALayout);
        jPanel2ALayout.setHorizontalGroup(
            jPanel2ALayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 0, Short.MAX_VALUE)
            .add(jPanel2ALayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPanel2ALayout.createSequentialGroup()
                    .add(0, 0, Short.MAX_VALUE)
                    .add(jLabel2)
                    .add(0, 0, Short.MAX_VALUE)))
        );
        jPanel2ALayout.setVerticalGroup(
            jPanel2ALayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 0, Short.MAX_VALUE)
            .add(jPanel2ALayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPanel2ALayout.createSequentialGroup()
                    .add(0, 0, Short.MAX_VALUE)
                    .add(jLabel2)
                    .add(0, 0, Short.MAX_VALUE)))
        );

        jFrame2A.getContentPane().add(jPanel2A, java.awt.BorderLayout.CENTER);

        jFrame3A.setAlwaysOnTop(true);
        jFrame3A.setBounds(new java.awt.Rectangle(1, 1, 150, 120));
        jFrame3A.setIconImages(null);
        jFrame3A.setUndecorated(true);
        jFrame3A.setResizable(false);
        jFrame3A.setType(java.awt.Window.Type.UTILITY);

        jPanel3A.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3A.setAlignmentX(1.0F);
        jPanel3A.setAlignmentY(1.0F);

        jLabel3.setFont(jLabel3.getFont().deriveFont(jLabel3.getFont().getSize()+10f));
        jLabel3.setLabelFor(jPanel1);
        jLabel3.setText("255");
        jLabel3.setName("sensor3"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel3ALayout = new org.jdesktop.layout.GroupLayout(jPanel3A);
        jPanel3A.setLayout(jPanel3ALayout);
        jPanel3ALayout.setHorizontalGroup(
            jPanel3ALayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 0, Short.MAX_VALUE)
            .add(jPanel3ALayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPanel3ALayout.createSequentialGroup()
                    .add(0, 0, Short.MAX_VALUE)
                    .add(jLabel3)
                    .add(0, 0, Short.MAX_VALUE)))
        );
        jPanel3ALayout.setVerticalGroup(
            jPanel3ALayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 0, Short.MAX_VALUE)
            .add(jPanel3ALayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPanel3ALayout.createSequentialGroup()
                    .add(0, 0, Short.MAX_VALUE)
                    .add(jLabel3)
                    .add(0, 0, Short.MAX_VALUE)))
        );

        jFrame3A.getContentPane().add(jPanel3A, java.awt.BorderLayout.CENTER);

        jFrame4A.setAlwaysOnTop(true);
        jFrame4A.setBounds(new java.awt.Rectangle(1, 1, 150, 120));
        jFrame4A.setIconImages(null);
        jFrame4A.setUndecorated(true);
        jFrame4A.setResizable(false);
        jFrame4A.setType(java.awt.Window.Type.UTILITY);

        jPanel4A.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4A.setAlignmentX(1.0F);
        jPanel4A.setAlignmentY(1.0F);

        jLabel4.setFont(jLabel4.getFont().deriveFont(jLabel4.getFont().getSize()+10f));
        jLabel4.setLabelFor(jPanel1);
        jLabel4.setText("255");
        jLabel4.setName("sensor4"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel4ALayout = new org.jdesktop.layout.GroupLayout(jPanel4A);
        jPanel4A.setLayout(jPanel4ALayout);
        jPanel4ALayout.setHorizontalGroup(
            jPanel4ALayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 0, Short.MAX_VALUE)
            .add(jPanel4ALayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPanel4ALayout.createSequentialGroup()
                    .add(0, 0, Short.MAX_VALUE)
                    .add(jLabel4)
                    .add(0, 0, Short.MAX_VALUE)))
        );
        jPanel4ALayout.setVerticalGroup(
            jPanel4ALayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 0, Short.MAX_VALUE)
            .add(jPanel4ALayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPanel4ALayout.createSequentialGroup()
                    .add(0, 0, Short.MAX_VALUE)
                    .add(jLabel4)
                    .add(0, 0, Short.MAX_VALUE)))
        );

        jFrame4A.getContentPane().add(jPanel4A, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Embedded Systems");
        setAlwaysOnTop(true);
        setAutoRequestFocus(false);
        setName(""); // NOI18N
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(100, 480));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(4, 0));

        jPanel1.setBackground(new java.awt.Color(0, 255, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setDoubleBuffered(false);
        jPanel1.setName("1"); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 120));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });

        jLabel5.setFont(jLabel5.getFont());
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Sensor 1");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setAlignmentX(0.0F);
        jPanel2.setAlignmentY(0.0F);
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setDoubleBuffered(false);
        jPanel2.setName("2"); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(160, 120));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Sensor 2");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 175, 175));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setAlignmentX(0.0F);
        jPanel3.setAlignmentY(0.0F);
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.setDoubleBuffered(false);
        jPanel3.setName("3"); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(160, 120));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Sensor 3");

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(0, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setAlignmentX(0.0F);
        jPanel4.setAlignmentY(0.0F);
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel4.setDoubleBuffered(false);
        jPanel4.setName("4"); // NOI18N
        jPanel4.setPreferredSize(new java.awt.Dimension(160, 120));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Sensor 4");

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel8, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel8, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel4);

        pack();
    }// </editor-fold>//GEN-END:initComponents
            
    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        sensor2.setVisible(true);        
        sensor2.setActive(sensor2Show);
        sensor2Show = !sensor2Show;
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        sensor3.setVisible(true);        
        sensor3.setActive(sensor3Show);
        sensor3Show = !sensor3Show;
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        sensor4.setVisible(true);        
        sensor4.setActive(sensor4Show);
        sensor4Show = !sensor4Show;
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        sensor1.setVisible(true);        
        sensor1.setActive(sensor1Show);
        sensor1Show = !sensor1Show;
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        posX=evt.getX();
        posY=evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        this.setLocation (evt.getXOnScreen()-posX,evt.getYOnScreen()-posY);
        
        jFrame1A.setLocation(evt.getXOnScreen()-posX + this.getWidth(),evt.getYOnScreen()-posY);
        jFrame2A.setLocation(evt.getXOnScreen()-posX + this.getWidth(),evt.getYOnScreen()-posY + jPanel1.getHeight());
        jFrame3A.setLocation(evt.getXOnScreen()-posX + this.getWidth(),evt.getYOnScreen()-posY + jPanel1.getHeight() * 2);
        jFrame4A.setLocation(evt.getXOnScreen()-posX + this.getWidth(),evt.getYOnScreen()-posY + jPanel1.getHeight() * 3);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jFrame1AMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFrame1AMouseDragged
//        int x = (sensor1.getLocation().x);
//        int y = (sensor1.getLocation().y);
//        int speed;
//        
//        speed = ((x < 0 && evt.getX() > xPos) ? 1 : -1);
//        
//        x+=speed;
//                
//        sensor1.setLocation(x, y);
//        
//        xPos = evt.getX();
    }//GEN-LAST:event_jFrame1AMouseDragged

    private void jFrame1AMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jFrame1AMouseWheelMoved
        //sensor1.setLocation(sensor1.getLocation().x + evt.getWheelRotation(), sensor1.getLocation().y);
    }//GEN-LAST:event_jFrame1AMouseWheelMoved

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jPanel1.setBackground(jPanel1.getBackground().darker());
        jPanel2.setBackground(jPanel2.getBackground().darker());
        jPanel3.setBackground(jPanel3.getBackground().darker());
        jPanel4.setBackground(jPanel4.getBackground().darker());
        
        jFrame1A.setBackground(jPanel1.getBackground());
        jFrame2A.setBackground(jPanel2.getBackground());
        jFrame3A.setBackground(jPanel3.getBackground());
        jFrame4A.setBackground(jPanel4.getBackground());
        
        jPanel1A.setBackground(jFrame1A.getBackground());        
        jPanel2A.setBackground(jFrame2A.getBackground());  
        jPanel3A.setBackground(jFrame3A.getBackground());  
        jPanel4A.setBackground(jFrame4A.getBackground());  
        
        sensor1.setBackground(jPanel1A.getBackground());
        sensor2.setBackground(jPanel2A.getBackground());
        sensor3.setBackground(jPanel3A.getBackground());
        sensor4.setBackground(jPanel4A.getBackground());
        
        int w = jPanel1.getWidth();
        int h = jPanel1.getHeight();
        
        Dimension d = new Dimension(w + (w) + 30, h);
                
        jFrame1A.setSize(d);
        jFrame2A.setSize(d);
        jFrame3A.setSize(d);
        jFrame4A.setSize(d);
        
        d = new Dimension(w + (w), h);
        jPanel1A.setSize(d);
        jPanel2A.setSize(d);
        jPanel3A.setSize(d);
        jPanel4A.setSize(d);
        
        sensor1.setSize(d);
        sensor2.setSize(d);
        sensor3.setSize(d);
        sensor4.setSize(d);
        
        Point p1 = jPanel1.getLocationOnScreen();
        Point p2 = jPanel2.getLocationOnScreen();
        Point p3 = jPanel3.getLocationOnScreen();
        Point p4 = jPanel4.getLocationOnScreen();
        
        jFrame1A.setLocation(p1.x + jPanel1.getWidth(), p1.y);
        jFrame2A.setLocation(p2.x + jPanel2.getWidth(), p2.y);
        jFrame3A.setLocation(p3.x + jPanel3.getWidth(), p3.y);
        jFrame4A.setLocation(p4.x + jPanel4.getWidth(), p4.y);
        
        int n = -d.width;
        sensor1.point = new Point(++n, 0);
        sensor2.point = new Point(++n, 0);
        sensor3.point = new Point(++n, 0);
        sensor4.point = new Point(++n, 0);
                        
        jFrame1A.setVisible(true);
        jFrame2A.setVisible(true);
        jFrame3A.setVisible(true);
        jFrame4A.setVisible(true);
    }//GEN-LAST:event_formWindowOpened
    // </editor-fold>
    
    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {                 
                new UI().setVisible(true);
            }
        });
    } 
    
    /* Declared Variables */
    //<editor-fold defaultstate="collapsed" desc=" Variables ">
    // Variables declaration - do not modify
    public static EmbeddedSensor sensor1;
    public static EmbeddedSensor sensor2;
    public static EmbeddedSensor sensor3;
    public static EmbeddedSensor sensor4;
    // End of variables declaration
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame jFrame1A;
    private javax.swing.JFrame jFrame2A;
    private javax.swing.JFrame jFrame3A;
    private javax.swing.JFrame jFrame4A;
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel1A;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel2A;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel3A;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel4A;
    // End of variables declaration//GEN-END:variables
//</editor-fold>
}
